INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10001, 'Rishabh', 'Noida', SYSDATE());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10021, 'Niwesh', 'Gurugram', SYSDATE());