INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10001, 'RISHABH', 'NOIDA', SYSDATE());

INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
VALUES (10021, 'NIWESH', 'GURUGRAM', SYSDATE());